SELECT * FROM TAB;

DESC EMPLOYEES;

SELECT * FROM EMPLOYEES;

-- 직원번호가 100인 사람을 출력
SELECT    *
    FROM  EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
-- King 이라는 직원 출력하기
SELECT  *
     From EMPLOYEES
     WHERE LAST_NAME = 'King';
 
-- 월급순으로 직원정보를 출력
-- EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY 4개를
-- 테이블 EMPLOYEES 에서 
-- 월급이 5000이상인 직원정보
-- SALARY 기준 내림차순으로 출력
SELECT      EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
    FROM    EMPLOYEES
    WHERE SALARY >= 5000
    ORDER BY SALARY DESC; -- 58

SELECT      EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
    FROM    EMPLOYEES
    ORDER BY SALARY DESC; -- 107
    
-- 전화번호에 100이 포함된 직원
SELECT      EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
    FROM    EMPLOYEES
    WHERE   PHONE_NUMBER LIKE '%100%';

-- 50번 부서의 직원을 출력해라
SELECT      EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
    FROM    EMPLOYEES
    WHERE   DEPARTMENT_ID = 50;
    
-- 부서가 없는 직원을 출력
SELECT      EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
    FROM    EMPLOYEES
    WHERE   DEPARTMENT_ID is NULL;
    
    
    